package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"tf-architect/internal/orchestrator"
	"tf-architect/internal/state"
	"tf-architect/internal/validation"
)

var (
	outputDir  string
	forceFlag  bool
	systemFile string
	noMaskFlag bool
	version    = "dev"
)

func main() {
	root := &cobra.Command{
		Use:     "tf-architect",
		Version: version,
		Short:   "Generate and validate production Terraform IaC from architecture documents",
		Long: `tf-architect turns architecture documents (PDF, DOCX, MD, TXT) into
production-grade AWS Terraform — and validates existing Terraform projects.

Typical workflow:

  1. Generate IaC from a document:
       tf-architect run architecture.pdf

  2. Validate the generated (or any existing) Terraform directory:
       tf-architect validate ./architecture-tf

  3. Check or resume an interrupted session:
       tf-architect status architecture.pdf

  4. Start fresh if needed:
       tf-architect reset architecture.pdf

Validation checks (in order):
  • terraform init    — initialises providers (no backend)
  • terraform validate — checks HCL syntax and references
  • tflint            — linting rules (skipped if not installed)
  • checkov           — security/compliance scan (skipped if not installed)
  • golden-rules-audit — enforces project conventions (S3 backend, tags,
                         no open ingress, no plaintext secrets, etc.)

Sessions are persisted: interrupted runs resume from the last checkpoint.`,
	}

	runCmd := &cobra.Command{
		Use:   "run <document>",
		Short: "Generate Terraform IaC from an architecture document",
		Long: `Reads an architecture document and generates production-grade AWS Terraform.

Claude analyses the document, asks clarifying questions when information is
missing, then generates each Terraform module. After generation it runs the
full validation suite and produces terraform-docs documentation.

Supported formats: PDF, DOCX, MD, TXT`,
		Example: `  # Generate into the default output directory (<docname>-tf/)
  tf-architect run architecture.pdf

  # Specify a custom output directory
  tf-architect run architecture.pdf --output ./infra/terraform

  # Force a full re-run (discard saved session)
  tf-architect run architecture.pdf --force

  # Use a custom system prompt / golden rules file
  tf-architect run architecture.pdf --system-file ./my-rules.md`,
		Args: cobra.ExactArgs(1),
		RunE: runGenerate,
	}
	runCmd.Flags().StringVarP(&outputDir, "output", "o", "", "Output directory for Terraform files (default: <docname>-tf/)")
	runCmd.Flags().BoolVarP(&forceFlag, "force", "f", false, "Force full re-run, ignoring saved session state")
	runCmd.Flags().StringVar(&systemFile, "system-file", "", "Path to custom system prompt file (default: embedded golden rules)")
	runCmd.Flags().BoolVar(&noMaskFlag, "no-mask", false, "Disable sensitive value masking (debug only — never use in production)")

	statusCmd := &cobra.Command{
		Use:   "status <document>",
		Short: "Show the session status for a document",
		Long: `Displays the current session state for a document: phase, last checkpoint,
generated files, and the result of the most recent validation run.`,
		Example: `  tf-architect status architecture.pdf`,
		Args:    cobra.ExactArgs(1),
		RunE:    runStatus,
	}

	resetCmd := &cobra.Command{
		Use:   "reset <document>",
		Short: "Delete the saved session state for a document",
		Long: `Removes the persisted session so the next 'run' starts from scratch.
Useful when you want to regenerate everything or the session is corrupted.`,
		Example: `  tf-architect reset architecture.pdf`,
		Args:    cobra.ExactArgs(1),
		RunE:    runReset,
	}

	validateCmd := &cobra.Command{
		Use:   "validate <terraform-dir>",
		Short: "Validate an existing Terraform project directory",
		Long: `Runs the full validation suite against any Terraform directory —
not just projects generated by tf-architect.

Checks performed (in order):
  1. terraform init     — downloads providers (no remote backend)
  2. terraform validate — syntax and reference errors
  3. tflint             — best-practice linting (skipped if not installed)
  4. checkov            — security and compliance policies (skipped if not installed)
  5. golden-rules-audit — project conventions:
       • S3 backend configured
       • required_version and required_providers pinned
       • default_tags present
       • no 0.0.0.0/0 ingress rules
       • no wildcard IAM actions (Action: *)
       • no plaintext secrets (password/token/api_key = "...")
       • no hardcoded AWS account IDs

The command exits with a non-zero status if any check fails.`,
		Example: `  # Validate a generated project
  tf-architect validate ./architecture-tf

  # Validate any existing Terraform directory
  tf-architect validate ~/projects/my-infra/terraform`,
		Args: cobra.ExactArgs(1),
		RunE: runValidate,
	}

	root.AddCommand(runCmd, statusCmd, resetCmd, validateCmd)
	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func runGenerate(cmd *cobra.Command, args []string) error {
	docPath, err := filepath.Abs(args[0])
	if err != nil {
		return fmt.Errorf("resolving document path: %w", err)
	}

	if _, err := os.Stat(docPath); os.IsNotExist(err) {
		return fmt.Errorf("document not found: %s", docPath)
	}

	workDir, _ := os.Getwd()

	if outputDir == "" {
		base := strings.TrimSuffix(filepath.Base(docPath), filepath.Ext(docPath))
		outputDir = filepath.Join(workDir, base+"-tf")
	}

	// Force re-run: delete existing session
	if forceFlag {
		hash, err := state.HashDoc(docPath)
		if err == nil {
			mgr := state.NewManager(workDir)
			sessionDir := filepath.Join(mgr.BaseDir, hash)
			if err := os.RemoveAll(sessionDir); err == nil {
				fmt.Printf("Cleared session for %s\n", filepath.Base(docPath))
			}
		}
	}

	systemPrompt := embeddedSystemPrompt()
	if systemFile != "" {
		data, err := os.ReadFile(systemFile)
		if err != nil {
			return fmt.Errorf("reading system file: %w", err)
		}
		systemPrompt = string(data)
	}

	orch := orchestrator.New(workDir, outputDir, systemPrompt, noMaskFlag)

	orch.OnStatus = func(msg string) {
		fmt.Println(msg)
	}

	orch.OnChunk = func(chunk string) {
		fmt.Print(chunk)
	}

	orch.OnQuestion = func(questions []string) []string {
		fmt.Println("\n── Clarification needed ─────────────────────")
		answers := make([]string, len(questions))
		reader := bufio.NewReader(os.Stdin)
		for i, q := range questions {
			fmt.Printf("\n[%d/%d] %s\n> ", i+1, len(questions), q)
			answer, _ := reader.ReadString('\n')
			answers[i] = strings.TrimSpace(answer)
		}
		fmt.Println("─────────────────────────────────────────────")
		return answers
	}

	return orch.Run(docPath)
}

func runStatus(cmd *cobra.Command, args []string) error {
	docPath, err := filepath.Abs(args[0])
	if err != nil {
		return fmt.Errorf("resolving document path: %w", err)
	}
	workDir, _ := os.Getwd()

	hash, err := state.HashDoc(docPath)
	if err != nil {
		return fmt.Errorf("hashing document: %w", err)
	}

	mgr := state.NewManager(workDir)
	sess, err := mgr.Load(hash)
	if err != nil {
		return err
	}
	if sess == nil {
		fmt.Printf("No session found for %s\n", filepath.Base(docPath))
		return nil
	}

	fmt.Printf("Document: %s\n", sess.DocPath)
	docHash := sess.DocHash
	if len(docHash) > 12 {
		docHash = docHash[:12] + "..."
	}
	fmt.Printf("Hash:     %s\n", docHash)
	fmt.Printf("Phase:    %s\n", sess.CurrentPhase)
	fmt.Printf("Created:  %s\n", sess.CreatedAt.Format("2006-01-02 15:04"))
	fmt.Printf("Updated:  %s\n", sess.UpdatedAt.Format("2006-01-02 15:04"))
	if sess.LastCheckpoint.GenerateStep != "" {
		fmt.Printf("Last step: %s\n", sess.LastCheckpoint.GenerateStep)
	}
	if len(sess.GeneratedFiles) > 0 {
		fmt.Printf("Generated: %d Terraform files\n", len(sess.GeneratedFiles))
	}
	if len(sess.ValidationRuns) > 0 {
		last := sess.ValidationRuns[len(sess.ValidationRuns)-1]
		result := "PASSED"
		if !last.Passed {
			result = "FAILED"
		}
		fmt.Printf("Last validation: %s (%s)\n", result, last.RunAt.Format("15:04"))
	}
	return nil
}

func runReset(cmd *cobra.Command, args []string) error {
	docPath, err := filepath.Abs(args[0])
	if err != nil {
		return fmt.Errorf("resolving document path: %w", err)
	}
	workDir, _ := os.Getwd()

	hash, err := state.HashDoc(docPath)
	if err != nil {
		return fmt.Errorf("hashing document: %w", err)
	}

	mgr := state.NewManager(workDir)
	sessionDir := filepath.Join(mgr.BaseDir, hash)
	if err := os.RemoveAll(sessionDir); err != nil {
		return fmt.Errorf("deleting session: %w", err)
	}
	fmt.Printf("Session for %s cleared.\n", filepath.Base(docPath))
	return nil
}

func runValidate(cmd *cobra.Command, args []string) error {
	dir, err := filepath.Abs(args[0])
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return fmt.Errorf("directory not found: %s", dir)
	}

	fmt.Printf("Validating: %s\n\n", dir)
	suite := validation.New(dir)
	results, runErr := suite.Run()

	passed, failed := 0, 0
	for _, r := range results {
		icon := "✓"
		if !r.Passed {
			icon = "✗"
			failed++
		} else {
			passed++
		}
		fmt.Printf("  %s  %s\n", icon, r.Stage)
		for _, e := range r.Errors {
			fmt.Printf("       %s\n", e)
		}
		if !r.Passed && r.Output != "" && len(r.Errors) == 0 {
			// print raw output for stages without structured errors (e.g. tflint)
			lines := strings.SplitN(strings.TrimSpace(r.Output), "\n", 6)
			for _, l := range lines {
				fmt.Printf("       %s\n", l)
			}
		}
	}

	fmt.Printf("\n%d passed, %d failed\n", passed, failed)
	if runErr != nil {
		return runErr
	}
	return nil
}

// embeddedSystemPrompt reads the system prompt from the prompts/ directory
// relative to the binary location, falling back to a minimal inline version.
func embeddedSystemPrompt() string {
	// Try relative to working directory first (dev mode)
	candidates := []string{
		"prompts/system.md",
		filepath.Join(filepath.Dir(os.Args[0]), "prompts/system.md"),
	}
	for _, path := range candidates {
		if data, err := os.ReadFile(path); err == nil {
			return string(data)
		}
	}
	// Minimal fallback — golden rules inline
	return `You are an expert AWS infrastructure engineer generating production-grade Terraform IaC.
Always configure S3 backend, pin provider versions, use default_tags, encrypt all storage,
never use 0.0.0.0/0 ingress, use least-privilege IAM, never hardcode secrets.
After each module write: STEP_COMPLETE:<module_name>`
}
